### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by martingasser**
Added cookie authentication for replication

### CODE REVIEW

**Comment by nraboy** [comment]
I'm not much of an iOS developer, but can you explain this change?:

```
NSOperationQueue.mainQueue
```

The listener seemed to work fine previously for iOS, so I'm wondering what this change did.  Is it just better practice?

Otherwise, your contribution looks good and I'll merge it after you respond.

Best,

cc @hodgreeley

**Comment by martingasser** [comment]
My bad. I accidentally linked against the development version of NativeScript. So it should still work with `.mainQueue()` and `.defaultCenter()` in NS 2.0.0.

Just for the records: For some reason, the function call syntax `NSOperationQueue.mainQueue()` was recently replaced with a static property.

Compare https://github.com/NativeScript/NativeScript/blob/682c465e5660b7eb231a896b16be47f6a1fd9ade/tns-core-modules/ios/objc-i386/objc!Foundation.d.ts with https://github.com/NativeScript/NativeScript/blob/f1f28745a80dc8d4f03f809d1127fd3a3fe481c6/tns-core-modules/ios/objc-i386/objc!Foundation.d.ts

`/* readonly */ static mainQueue: NSOperationQueue;`

Previously it was declared as

`static mainQueue(): NSOperationQueue;`

Same for `NSNotificationCenter.defaultCenter`.

**Comment by nraboy** [comment]
Just to confirm though, both versions will work, but your version is accommodating the future.  Is this correct?

**Comment by martingasser** [comment]
I've added checks (using utils.ios.getter) to determine whether the API's are exposed as methods or properties.

This should make it future-proof (and compatible with older versions of NativeScript as well).

**Comment by nraboy** [comment]
Should I merge now?

**Comment by martingasser** [comment]
Yes.

**Comment by nraboy** [comment]
Thank you for contributing!

**Comment by derekdon** [comment]
Great stuff! Has this been npm published?

**Comment by nraboy** [comment]
I'll probably publish to NPM later this week.  I need to update the demo apps and would like to do at same time.

**Comment by derekdon** [comment]
@nraboy that's understandable... Thanks. I'm very new to nativescript and don't fully understanding what wiring / setup running something like "tns plugin add nativescript-couchbase" does behind the scenes. I'm curious if in the meantime I can do something like "tns plugin add https://github.com/couchbaselabs/nativescript-couchbase.git", and will that still work? Or if I should just clone the project and run one of the build scripts and npm link to it for now.

**Comment by nraboy** [comment]
I set the repository to ignore JS files, so adding the plugin directly from GitHub will not work.  You'll have to clone the repository, run the build script, then add the local directory to your project if you wish to use the master branch rather than a version.

Best,

**Comment by derekdon** [comment]
@nraboy thanks for the advice. I've tried what I assume is the correct workflow: 
```
cd workspace/
git clone https://github.com/couchbaselabs/nativescript-couchbase.git
cd nativescript-couchbase/
npm run build // < fails with error below
cd ../project/
tns plugin add ../nativescript-couchbase
tns run android --emulator
```
This is the error the build step reports: 

```
> nativescript-couchbase@1.0.11 build workspace/nativescript-couchbase
> tsc

couchbase.ios.ts(158,37): error TS2339: Property 'getter' does not exist on type 'typeof ios'.
couchbase.ios.ts(159,33): error TS2339: Property 'getter' does not exist on type 'typeof ios'.

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! nativescript-couchbase@1.0.11 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the nativescript-couchbase@1.0.11 build script 'tsc'.
npm ERR! This is most likely a problem with the nativescript-couchbase package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nativescript-couchbase
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls nativescript-couchbase
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     workspace/nativescript-couchbase/npm-debug.log
```
Is this expected, or is there another way I should be building this project? Like I said I'm quite new to NativeScript.

From debugging the app I see it errors not finding this function:

this.replicator.setCookieNamedWithValuePathExpirationDateSecure

**Comment by martingasser** [comment]
@derekdon could you please try this branch from my fork?

https://github.com/martingasser/nativescript-couchbase/tree/authentication

Thank you.

**Comment by derekdon** [comment]
@martingasser Following these steps...

```
cd workspace/
git clone https://github.com/martingasser/nativescript-couchbase.git
cd nativescript-couchbase/
git checkout authentication
npm install
tns install
npm run setup
npm run prepare
npm run build
cd ../project/
tns plugin remove nativescript-couchbase // old
tns plugin add ../nativescript-couchbase // new
```
...it now executes error free, however I'm not sure if there's a step missing as I still can't see the setCookieNamedWithValuePathExpirationDateSecure function in the project source deps.

On running the project:

```
tns run android --emulator
```

It throws the same error re setCookieNamedWithValuePathExpirationDateSecure being undefined.

Any ideas?

**Comment by derekdon** [comment]
I just tried to run the ios demo app incase it was an android specific issue. However I get an error about not being able to find a timers module.

```
** BUILD SUCCEEDED **

Project successfully built
Successfully deployed on device with identifier '516DA38C-56BE-459D-938F-DF9405CAB16D'.
Sep 30 23:20:25 Dereks-MacBook-Pro ngdemo[6292]: 1   0x10695fc77 -[TNSRuntime executeModule:]
Sep 30 23:20:25 Dereks-MacBook-Pro ngdemo[6292]: 2   0x1062a5f2f main
Sep 30 23:20:25 Dereks-MacBook-Pro ngdemo[6292]: 3   0x10a79692d start
Sep 30 23:20:25 Dereks-MacBook-Pro ngdemo[6292]: file:///app/tns_modules/zone.js/dist/zone-node.js:958:21: JS ERROR Error: Could not find module 'timers'. Computed path '/Users/derekdon/Library/Developer/CoreSimulator/Devices/516DA38C-56BE-459D-938F-DF9405CAB16D/data/Containers/Bundle/Application/4ACAE12D-7BAE-4DF2-963F-8226F9B7AED3/ngdemo.app/app/tns_modules/timers'.
Sep 30 23:20:25 Dereks-MacBook-Pro com.apple.CoreSimulator.SimDevice.516DA38C-56BE-459D-938F-DF9405CAB16D.launchd_sim[6066] (UIKitApplication:org.nativescript.ngdemo[0xab43][6292]): Service exited due to signal: Segmentation fault: 11
```
@nraboy is this expected / one of the reasons you mentioned needing to update the demo apps? or did you just mean you wanted to add setCookie to them?

@martingasser I see you've made a change to the android api call after my previous comment. https://github.com/martingasser/nativescript-couchbase/commit/69b007c8fcdc0358eb00b24afc9188e4d2d6cc6d, Is this only required on the android side as the ios version is still referencing replicator methods setCookieNamedWithValuePathExpirationDateSecure and deleteCookieNamed?

**Comment by martingasser** [comment]
@derekdon yes, the iOS runtime maps ObjC methods to JavaScript by concatenating all parameter names. On Android the mapping from Java to JavaScript is almost 1:1.

**Comment by derekdon** [comment]
@martingasser Ah good to know! Thanks.

In terms of getting this working, I think I'm going to have to admit defeat! 

```
JS: About to call setCookie
JS: java.lang.Exception: Failed resolving method setCookie on class com.couchbase.lite.replicator.Replication
JS:     com.tns.Runtime.resolveMethodOverload(Runtime.java:816)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:716)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:697)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:687)
JS:     com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(org.nativescript.widgets.Async$CompleteCallback.java)
JS:     org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:465)
JS:     org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:379)
JS:     android.os.AsyncTask.finish(AsyncTask.java:632)
JS:     android.os.AsyncTask.access$600(AsyncTask.java:177)
JS:     android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:136)
JS:     android.app.ActivityThread.main(ActivityThread.java:5017)
JS:     java.lang.reflect.Method.invokeNative(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:515)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
JS:     dalvik.system.NativeStart.main(Native Method)
JS: EXCEPTION: Uncaught (in promise): Error: Error in ./ListComponent class ListComponent_Host
```
That's using the latest version of your authentication branch, running on android emulator.

I wasn't sure where couchbase lite was actually being stored on the file system as I couldn't see it in the project. However I found a couple of references to it in the gradle cache.

```
~/.gradle/caches/modules-2/files-2.1/com.couchbase.lite/couchbase-lite-android/1.0.3.1/
~/.gradle/caches/modules-2/files-2.1/com.couchbase.lite/couchbase-lite-android/1.2.0/
~/.gradle/caches/modules-2/files-2.1/com.couchbase.lite/couchbase-lite-android-sqlite-default/1.2.0/
~/.gradle/caches/modules-2/files-2.1/com.couchbase.lite/couchbase-lite-java-core/1.0.3.1/
~/.gradle/caches/modules-2/files-2.1/com.couchbase.lite/couchbase-lite-java-core/1.2.0/
```
I'm not sure why there are two versions, both listed as updated yesterday.

I assume you can call the setCookie method without issue on android?

**Comment by martingasser** [comment]
@derekdon the trick was to call the native setCookie method with a java.util.Date instance.

68f907a82361b3661007e82eb8acf922bd36f0f5 should work for iOS and Android.

**Comment by nraboy** [comment]
@martingasser and @derekdon,

I've updated both **demo** and **ng-demo** to work with the latest versions of NativeScript.  The merge that @martingasser had submitted was not working for iOS due to the `getter` error that @derekdon reported.  I've copied some code from @martingasser repository which seems to have fixed it for now.

@martingasser, where do we stand with the iOS stuff?  Can you check to make sure the upstream has the correct code?  I'm not much of an iOS guy (more Android) so you might know better than I do.

Best,

**Comment by martingasser** [comment]
@nraboy I integrated my changes with your master, I'll submit a PR. Works in Android and iOS.

**Comment by derekdon** [comment]
@nraboy and @martingasser I want to take this for a spin now to see what's what... but I'm not 100% what repo / branch / npm module I should be testing now? Based on @martingasser last comment, I'm going to start by pulling those changes down first and see if that works.

**Comment by martingasser** [comment]
@derekdon either master or the authentication branch. The latter also contains a modified demo that sketches how to do session auth with CB sync gateway.

**Comment by derekdon** [comment]
@nraboy and @martingasser I'm happy to report using @martingasser's master branch now works as expected, in the android emulator at least. I will try ios tomorrow.

I am seeing an issue that I wonder if you guys are also seeing.

```
Couchbase.prototype.executeQuery = function (viewName, options) {
var query = this.database.getView(viewName).createQuery();
...
var result = query.run(); // < Causing the following error message (sometimes)
...
}
```

```
JS: this.database.executeQuery('people')
W/System.err( 3744): 	at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 3744): 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
W/System.err( 3744): 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
W/System.err( 3744): 	at com.tns.Runtime.callJSMethod(Runtime.java:716)
W/System.err( 3744): 	at com.tns.Runtime.callJSMethod(Runtime.java:697)
W/System.err( 3744): 	at com.tns.Runtime.callJSMethod(Runtime.java:687)
W/System.err( 3744): 	at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 3744): 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
W/System.err( 3744): 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
W/System.err( 3744): 	at com.tns.Runtime.callJSMethod(Runtime.java:716)
W/System.err( 3744): 	at com.tns.Runtime.callJSMethod(Runtime.java:697)
W/System.err( 3744): 	at com.tns.Runtime.callJSMethod(Runtime.java:687)
```
Let me know.

Thanks for your help so far...

**Comment by arolando** [comment]
Hi @nraboy and @martingasser, I'm trying to use the authentication for the nativescript couchbase module, but I don't understand how to use, can you provide an example?

Thanks in advance.

**Pull request merged**
