### PR TITLE
Fix webpack module error

### PR DESCRIPTION
**Pull request by hypery2k**
Resolve issues with webpack error:
```
Module not found: Error: Can't resolve 'nativescript-couchbase'
```

Would be nice to really great a new version soon, as this issue is a real big problem for us

### CODE REVIEW

**Comment by nraboy** [comment]
Have you confirmed that this still works with and without Webpack?

**Comment by hypery2k** [comment]
in my local sample projects it worked with and without webpack

**Comment by nraboy** [comment]
Thanks for contributing!

**Comment by hypery2k** [comment]
you're welcome

**Pull request merged**
