### PR TITLE
setCookie() fixes for iOS and Android

### PR DESCRIPTION
**Pull request by martingasser**

### CODE REVIEW

**Comment by martingasser** [comment]
Sorry, it's corrected.

**Comment by nraboy** [comment]
Thanks for contributing!

Any interest in adding anything to the demo applications to reflect the change?  Even if it remains in a comment.

**Comment by martingasser** [comment]
I have a modified demo on my `authentication` branch that shows how to get a session from the sync gateway REST API and how to use the setCookie() API. Should I merge it with the current demo on master? Or would it be better to have a separate authentication demo?

**Comment by nraboy** [comment]
What do you advise @martingasser?  I'm open to both scenarios (a new demo, or integrated).

**Comment by martingasser** [comment]
I think an extra demo would be better. I'll see what I can do.

Best

**Comment by nraboy** [comment]
Awesome!

**Pull request merged**
