### PR TITLE
Null Check for Deleted Objects

### PR DESCRIPTION
**Pull request by mehfuzh**

### CODE REVIEW

**Comment by nraboy** [comment]
A few things:

1. Does Android not need he same fix as iOS?
2. You created a new ng-demo page, but it already exists elsewhere.  Why?
3. Let's do everything on the development branch to prevent breaking changes.

**Comment by mehfuzh** [comment]
Hey Nick,

Please find my answers below:

A few things:

Does Android not need he same fix as iOS? => I dont think so as it is an iOS specific issue.
You created a new ng-demo page, but it already exists elsewhere. Why? => I think that its a mistake I will remove it.
Let's do everything on the development branch to prevent breaking changes => Agreed.

**Comment by nraboy** [comment]
Alright, remove it and PR to the `development` branch and I will merge it.

**Comment by nraboy** [comment]
Merged to development here https://github.com/couchbaselabs/nativescript-couchbase/pull/29

**Pull request closed without merging**
