### PR TITLE
Attachment handling methods

### PR DESCRIPTION
**Pull request by triniwiz**

### CODE REVIEW

**Comment by nraboy** [comment]
Thanks @triniwiz!

Before I merge this, @mehfuzh, would you be able to convert Osei's Android enhancements to iOS?  I want to keep the two in sync.

Please let me know.

Thanks,

**Comment by mehfuzh** [comment]
I will look at this today

**Comment by nraboy** [comment]
@triniwiz can I have you remove the README information until it works for both Android and iOS?  Just so we can avoid confusion for now.  Leave the Android code though.

**Comment by triniwiz** [comment]
ok no problem

**Comment by nraboy** [comment]
Thanks!

@mehfuzh, it was merged.  We left it out of the README, but should you have a usage question I am sure @triniwiz would share.  I looked at his code, it seems slick.

**Comment by mehfuzh** [comment]
@triniwiz by any chance is the demo app updated so that I can test it for behaviors in order to implement for iOS

**Comment by triniwiz** [comment]
@mehfuzh no i did not update the demo

**Comment by nraboy** [comment]
@triniwiz can you create a branch `development` that contains documentation in the README and code in the demo?  Then @mehfuzh can work on the iOS portion from the `development` branch before we merge with the master.

**Pull request merged**
