### PR TITLE
Update to 1.4.1, enabled encryption, fixed iOS error handling

### LINKED ISSUE #45: Enable Encryption
Hi, i'm trying to enable encryption in the plugin and as you can check in this [commit](https://github.com/NMA-SPMS/nativescript-couchbase/commit/04ae31ace2bdbb8943ba1ec3441794d68f4726eb) and i'm having some issues with ios runtime, so far i have updated the couchbase lite version and added sqlcipher lib too,
in the android side everything works ok, but in ios i can't get an instance of CBLDatabaseOptions

`Can't find variable: CBLDatabaseOptions`

`CBLDatabaseOptions` is in the `CBLManager.h:23`(couchbase headers files) 

btw i have deleted the static couchbase lite lib and added a PodFile with the 2 dependencies

And another question is the build.xcconfig, in the commit i removed the `-lsqlite3`, but when i'm usin the plugin in the ng-demo xcode adds it again, how can i prevent this ?

Thanks in advance, as soon as this is resolved i will make a pr with the changes

### PR DESCRIPTION
**Pull request by aboganas**
- [x] updated binaries to latest couch base lite 1.4.1
- [x] correctly linked SQLCipher
- [x] extended constructor to create encrypted database
- [x] added create option in contractor to retrieve only existing database
- [x] added closeDatabase function
- [x] fixed iOS error handling bugs were errors like conflict were not shown to the user.

TO do in future PR:
-  Compound keys
-  Live query
-  Conflict management
-  Attachment

PS: I didn't touch the demo apps since I'm not an Angular guy, I tested all the functionality on my own app.
* ensure CocoaPods are updated since this couch base version is the latest

Closes #45

### CODE REVIEW

**Comment by nraboy** [comment]
Thanks for contributing! I'm out at an event this week, but I'll review this PR early next week. Ping me if you haven't heard from me by the end of next week.

Best,

**Comment by aboganas** [comment]
did you have a chance to take a look at it?

**Comment by aboganas** [comment]
Ok I switched to using this [couchbase plugin]( https://www.npmjs.com/package/nativescript-couchbaselite) instead after its maintainer updated the usage licence, so you can close this PR. 
Thanks

**Comment by dalsscarlon** [comment]
any updates on this PR?? I really need it, thanks.

**Comment by alexandruantonica** [comment]
Any updates on this PR ?

**Comment by aboganas** [comment]
@dalsscarlon @alexandruantonica When I submitted this PR I tested it throughly and everything works fine; however, it doesn't seem it gonna be merged so you can fork it and use it in your fork.

Myself I'll not be working on this PR any further as I moved to using [this plugin](https://github.com/nabil-mansouri/nativescript-couchbaselite) instead.

**Comment by jfr3000** [comment]
@nraboy what's the status of this PR?

**Comment by borrrden** [comment]
The status of this repo is "unmaintained"

**Pull request closed without merging**
